language: swift
osx_image: xcode10.1
xcode_workspace: GithubIssueViewer.xcworkspace
xcode_scheme: GithubIssueViewer
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
install: pod repo update
